### ISSUE TITLE
ld  crashes in some condition

### ISSUE THREAD

**Issue by kas1e** [migthymax/binutils-gdb#8] opened 2023-08-19 16:08 UTC
Playing around with crash we have when use -use-dynld, find out, that "ld" called with a little bit different paramters in compare with when we build "static" things.

So we take very simple test case (basically, one can take simple hello_world.c, then -S on it to have assembler output, and doing the same "as" and "ld", i just choose a more simple case).

```
   .globl main
main:
        lis %r3,.msg@ha          #
        la %r3,.msg@l(%r3)       # printf("aaaa");
        bl printf                #

        li %r3,0                 # exit(0);
        bl exit                  #

.msg:
        .string "aaaa"
```

Now, build object:

```ppc-amigaos-as test.s -o test.o```

Next, try to link binary this way (be it for clib2, or newlib, crash the same):

```ppc-amigaos-ld  test.o -o test -L/usr/local/amiga/ppc-amigaos/SDK/clib2/lib /usr/local/amiga/ppc-amigaos/SDK/clib2/lib/crtbegin.o /usr/local/amiga/ppc-amigaos/SDK/clib2/lib/crtend.o -lc```

Bang, and we crash. That the way we do linking when -use-dynld used (with -lc , -lgcc at the end, together with pointing out on the libs with -L).

BUT!  if we link like this :

```ppc-amigaos-ld  test.o -o test /usr/local/amiga/ppc-amigaos/SDK/newlib/lib/crtbegin.o /usr/local/amiga/ppc-amigaos/SDK/newlib/lib/LibC.a /usr/local/amiga/ppc-amigaos/SDK/newlib/lib/crtend.o```

then no crash, and all fine.

The difference between crashed and no crashed version, is that we add -lc together with -L path to the libs.

If i just regroup  to remove -L dir, and -lc at end, and replace on the full path to the libc.a , then it also works ! 

Adtool's version of LD of course reacts correctly in that terms, no crash in any scenario.

Maybe when we use -L and -lc at end, then .so version of the library attached and that cause a crash ?

**Comment by kas1e** [comment] 2023-08-19 18:44
Some more info : it is indeed about .sobjs.  When we use -L/dir_to_libs + -llib at the end, then LD firstly take the .so onboard (and crashes). If i simply rename clib2/libc.so from SDK (or newlib/libc.so, that same issues) - then even with -L and -lc it attach .a version of library and didn't crash.

So, the issue is exactly with linking together with .sobjs

**Comment by kas1e** [comment] 2023-08-22 19:22
After [Rework how PLT is handled](https://github.com/migthymax/binutils-gdb/commit/05ee42fb60d2fa0166fc04e9ea27d0abd4abe593) , we have no more crash when link against .so files, but, resulting binaries simple crashes on running (while adtool's binutils produce working binary).

I create an arhive, in which you have 3 dirs : sources , adtools_ld and new_ld. In both ld directories i put all the  .so, .o and ready test binaires to run build on adtools and our new binutils, so everything can be compared. 

As far as i can see, the difference is that after ".plt" sections, we seems didn't have null termination or something, and some sections sits in the same segment. But it's better to compare ready binaries. Archive attached.

[capehill.zip](https://github.com/migthymax/binutils-gdb/files/12412272/capehill.zip)

**Comment by kas1e** [comment] 2023-08-25 07:19
After merging of "fini/init" branch to "ld-crash" branch, we do have 2 new issues:

1. compilation broken in GDB parts:
```
../../gnulib/import/unistd.h:663:3: error: #error "Please include config.h first."
  663 |  #error "Please include config.h first."
      |   ^~~~~
../../gnulib/import/unistd.h:665:24: error: expected ‘;’ before ‘extern’
  665 | _GL_INLINE_HEADER_BEGIN
      |                        ^
      |                        ;
../../gnulib/import/unistd.h:2830:22: error: expected ‘;’ before ‘extern’
 2830 | _GL_INLINE_HEADER_END
      |                      ^
```

I fixed it based on this: https://pi.simark.ca/gdb-patches/20211008201657.630932-1-cbiesinger@google.com/T/

So had to add ```#include "defs.h"``` right at top of those 3 files: interrupts.c, thee.c and sim_calls.c , and then compilation goes fine.

2. Issue #2 : crash with LD still there  (test case binaries in previous post). But, we have one more new issue: now, when we link with .so, we do have ```/usr/local/amiga/bin/ppc-amigaos-ld: warning: libf.so has a LOAD segment with RWX permissions```. Just like when we use -N option. Probably related to the fact of touched default LDScript options in the ld/emulparams/amigaos.sh.

**Comment by migthymax** [comment] 2023-08-29 14:12
The cause is that with the newer binutils the .rodata section has been merged into the the .text section.

The .text section under normal circumstance is write protected. As the name of the .rodata section implies (read-ony data) it shouldn't cause any troubles. But for sobjs, there seems to be relocation in use, which works on the .rodata section, aka modifies it. Which fails!

Thus the .rodata section is no moved into a writable section with commit [Maked the .rodata section being put into a writable segment.
](https://github.com/migthymax/binutils-gdb/commit/3707231f48b69a26b3491f7dc649596af156e9c0)

**Closed by migthymax** 2023-08-29 14:12 UTC

**Comment by migthymax** [comment] 2023-09-13 09:48
The solution to put .rodata writable, is just a bad workaround. A better approach is to put it in its own segment: 
[Enforce that the .rodata section is put its own read-only segment (program header)](https://github.com/migthymax/binutils-gdb/commit/a5c73623197dbfee5aa3a07b1e0f8d8865097074)

The reason for that is, that the elf.library don't load a segment complete if the segment contains the .rodata section,
see https://www.amigans.net/modules/newbb/viewtopic.php?post_id=142710#forumpost142710

**Comment by kas1e** [comment] 2023-09-16 10:10
Just so it's not forgotten : the https://github.com/migthymax/binutils-gdb/commit/a5c73623197dbfee5aa3a07b1e0f8d8865097074 do not create rodata in own segment, instead, it put to the same set of segments as before together with .text , .plt and co. That how it looks like now again:

```
Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  PHDR           0x000034 0x01800034 0x01800034 0x000a0 0x000a0 R   0x4
  INTERP         0x0000d4 0x018000d4 0x018000d4 0x00011 0x00011 R   0x1
      [Requesting program interpreter: /usr/lib/ld.so.1]
  LOAD           0x000000 0x01800000 0x01800000 0x03a58 0x03a58 R E 0x10000
  LOAD           0x003a58 0x01813a58 0x01813a58 0x000d0 0x00194 RWE 0x10000
  DYNAMIC        0x003a68 0x01813a68 0x01813a68 0x000b0 0x000b0 RW  0x4

 Section to Segment mapping:
  Segment Sections...
   00
   01     .interp
   02     .interp .hash .dynsym .dynstr .rela.dyn .rela.plt .text .rodata .__newlib_version
   03     .ctors .dtors .dynamic .data .got .sbss .plt .bss
   04     .dynamic
```
